M48
; DRILL file {KiCad 7.0.11-2.fc38} date Wed 10 Apr 2024 19:42:02 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-10T19:42:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-2.fc38
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.0551Y-4.0551
X4.0551Y-5.7874
X7.7559Y-4.0551
X7.7559Y-5.7874
M30
